### ISSUE TITLE
[BUG, WORKAROUND] TaskTimer.vala fails to build with valac 0.56, with the error "value is less accessible than constant"

### ISSUE THREAD

**Issue by ernstki** [mank319/Go-For-It#152]
Build fails on elementary OS 7.1 Horus (Ubuntu 22.04) with the following error:

```
/path/to/Go-For-It/src/Services/TaskTimer.vala:35.42-35.50: error: value is less accessible than constant `GOFI.TaskTimer.UPDATE_INTERVAL'
   35 |     public const int64 UPDATE_INTERVAL = 60 * US_C;
      |                                          ^~~~~~~~~ 
```

### To Reproduce

```console
$ git clone https://github.com/Manuel-Kehl/Go-For-It.git
$ cd Go-For-It
$ cmake --install-prefix /usr/local -B build
$ cd build && make
[  1%] Generating Constants.c;Date.c;Utils.c;ListIdentifier.c;TodoListInfo.c;Schedule.c;…
/path/to/Go-For-It/src/Services/TaskTimer.vala:35.42-35.50: error: value is less accessible than constant `GOFI.TaskTimer.UPDATE_INTERVAL'
   35 |     public const int64 UPDATE_INTERVAL = 60 * US_C;
      |                                          ^~~~~~~~~ 
Compilation failed: 1 error(s), 0 warning(s)
gmake[2]: *** [src/CMakeFiles/com.github.jmoerman.go-for-it-0.dir/build.make:296: src/com.github.jmoerman.go-for-it-0_valac.stamp] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:153: src/CMakeFiles/com.github.jmoerman.go-for-it-0.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

### Workaround

via JMoerman/Go-For-It#172 and JMoerman/Go-For-It#173:

```
cd Go-For-It
PATCH=https://patch-diff.githubusercontent.com/raw/JMoerman/Go-For-It/pull/173.diff
wget $PATCH || curl -LOJ $PATCH
patch -p1 < 173.diff
cd build && make
sudo make install |& tee ../install.log  # so you can uninstall later
```

### OS and application version

* elementary OS 7.1 Horus (Ubuntu 22.04)
* CMake 3.22.1
* valac 0.56.17 from system default repositories

### Additional context

I did _eventually_ see the statement in the "About" section of the repo, and it _is_ reiterated in the issue template, but I still managed to overlook the fact that active development is happening in some other repository.

For the benefit of others who are similarly confused, I'm duplicating JMoerman/Go-For-It#172 and its workaround here anyway, so it can be found with a search, and I will close this issue immediately after opening it.
